services:
  db:
    image: postgres:15-alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  web:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["npx", "prisma", "studio", "--port", "5555"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: