FROM node:slim

RUN apt-get update -y \
&& apt-get install -y openssl

WORKDIR /app

COPY package.json ./

COPY . .

RUN npm ci

CMD ["sh", "-c", "npm run db:deploy && npm run build && npm run start"]