ARG NODE_VERSION=22.16.0
FROM node:${NODE_VERSION}-alpine

WORKDIR /app
COPY package.json ./
RUN npm install

COPY . .

# Setup Database
RUN npx prisma generate
RUN npx prisma migrate deploy
RUN npx prisma db push
RUN npx prisma db seed

# Build the application
EXPOSE 3000
CMD ["npm", "run", "start"]